# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ImageFetchFromApi' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ImageFetchFromApi
   pod 'TPKeyboardAvoiding'
   pod 'AlamofireImage'
   pod 'ReachabilitySwift'
   pod 'AlamofireObjectMapper'
   pod 'ObjectMapper'
   pod 'SVProgressHUD'
   pod 'SwiftyJSON'
   pod 'JSONWebToken'
   pod 'SwiftyUserDefaults'
   pod 'SDWebImage'
   #  pod 'Kingfisher'


end
