# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ThirdPartyApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ThirdPartyApp
    pod 'ActiveLabel',' 0.9.0'

end
