# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIExperiments' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for UIExperiments
    pod 'TPKeyboardAvoiding', '~> 1.3.1'


end
